version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: farmflow-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: farmflow
      POSTGRES_USER: farmflow
      POSTGRES_PASSWORD: farmflow1234
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  influxdb:
    image: influxdb:2.7
    container_name: farmflow-influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: farmflow
      DOCKER_INFLUXDB_INIT_PASSWORD: farmflow1234
      DOCKER_INFLUXDB_INIT_ORG: farmflow-org
      DOCKER_INFLUXDB_INIT_BUCKET: sensor_data
      DOCKER_INFLUXDB_INIT_RETENTION: 168h
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: farmflow-influx-token-2026
    volumes:
      - influx_data:/var/lib/influxdb2

  redis:
    image: redis:7-alpine
    container_name: farmflow-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  influx_data:
  redis_data: