# 1. PostgreSQL DB 설정
spring.datasource.url=jdbc:postgresql://192.168.34.27:5432/farmflow
spring.datasource.username=farmflow
spring.datasource.password=farmflow1234

# 2. InfluxDB (시계열 데이터) 설정
spring.influx.url=http://192.168.34.27:8086
spring.influx.token=farmflow-influx-token-2026
